{% set version = "1.1.1.2" %}

package:
  name: click-plugins
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/click-plugins/click_plugins-{{ version }}.tar.gz
  sha256: d7af3984a99d243c131aa1a828331e7630f4a88a9741fd05c927b204bcf92261

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - click >=3.0
  run:
    - python >={{ python_min }}
    - click >=3.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - click_plugins

about:
  home: https://github.com/click-contrib/click-plugins
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'An extension module for click to enable registering CLI commands via setuptools entry-points'

extra:
  recipe-maintainers:
    - ocefpaf
